spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: springSecurity
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
